/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import TransporterUnits.KeyDTO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import steam.jewishs.steamkeysmaven.KeyManager;


public class Trade extends javax.swing.JFrame {
    
    private List<KeyDTO> keys;
    DefaultTableModel modelotabla;
    
    public void setKeys(List<KeyDTO> keys){
        this.keys = keys;
    }
    
    
    public Trade() {
        initComponents();
        this.setSize(Inventory.getLastWindow().getSize());
        this.setLocationRelativeTo(Inventory.getLastWindow()); 
        initTrade();
    }
    private void initStorePrice(){
        PriceImput.setValue(0.0);
    }
        private boolean isDouble(String str) {
        return (str.matches("[+-]?\\d*(\\.\\d+)?") && str.equals("")==false);
    }
    private double getDoubleInput() throws Exception{
        String input = PriceImput.getText(); ///
        if(isDouble(input) && Double.parseDouble(input)>=0.0){
            return Double.parseDouble(input);
        }else{
            throw new Exception("bad enter");
        }
    } 
    private void MessageDialog(String scr){
        JOptionPane.showMessageDialog(this, scr);
    }
    private void initTrade(){
        initStorePrice();
        ListTable();
    }
    private void ListTable(){
        try {
            double storeprice = getDoubleInput();
            double keyprice = KeyManager.findParameter("KeysPrice").getValue();
            double razon = keyprice/storeprice;
            //MODELO
            String[] columnames = {"Store Price","VMR"}; 
            modelotabla = new DefaultTableModel(null, columnames);
            //LLENADO DE LA TABLA
            for(double i = 0.05; i< 10.01; i= i+0.01){
                double calculated = i*razon;
                Object[] row = {i,calculated};
                modelotabla.addRow(row);
            }
            
        } catch (Exception ex) {
            MessageDialog("Failed. Bad enter");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PriceTittle = new javax.swing.JLabel();
        PriceImput = new javax.swing.JFormattedTextField();
        TradeTittle = new javax.swing.JLabel();
        VmrScroll = new javax.swing.JScrollPane();
        VmrTable = new javax.swing.JTable();
        SellPriceImput = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        BalanceImput = new javax.swing.JTextField();
        ListScroll = new javax.swing.JScrollPane();
        TradeListTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        TradeButton = new javax.swing.JButton();
        BalanceTittle = new javax.swing.JLabel();
        ReloadButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PriceTittle.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PriceTittle.setText("KeyPrice");

        PriceImput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        PriceImput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PriceImput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceImputActionPerformed(evt);
            }
        });

        TradeTittle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        TradeTittle.setText("Trade");

        VmrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        VmrTable.setFocusable(false);
        VmrTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        VmrScroll.setViewportView(VmrTable);

        SellPriceImput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SellPriceImput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellPriceImputActionPerformed(evt);
            }
        });

        AddButton.setText(">>>");
        AddButton.setFocusable(false);

        BalanceImput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BalanceImput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        TradeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TradeListTable.setFocusable(false);
        ListScroll.setViewportView(TradeListTable);

        BackButton.setText("Back");
        BackButton.setFocusable(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        TradeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TradeButton.setText("Trade");
        TradeButton.setFocusable(false);

        BalanceTittle.setText("Balance");
        BalanceTittle.setToolTipText("");
        BalanceTittle.setFocusable(false);

        ReloadButton.setText("Reload");

        DeleteButton.setText("Delete");
        DeleteButton.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(TradeTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(VmrScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(PriceTittle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PriceImput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReloadButton)
                        .addGap(302, 302, 302))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BalanceImput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(TradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BalanceTittle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DeleteButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(SellPriceImput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(AddButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(ListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(22, 22, 22)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(TradeTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceTittle)
                    .addComponent(PriceImput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReloadButton))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BalanceTittle, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BalanceImput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VmrScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SellPriceImput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddButton)
                .addGap(223, 223, 223))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void PriceImputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceImputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceImputActionPerformed

    private void SellPriceImputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellPriceImputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellPriceImputActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       Inventory.CloseLastWindow();
       Inventory inventory = (Inventory) Inventory.getLastWindow();
       inventory.setLocationRelativeTo(this);
       inventory.ReloadTable();
       inventory.setVisible(true);
       dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Trade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Trade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Trade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Trade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Trade().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BalanceImput;
    private javax.swing.JLabel BalanceTittle;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JScrollPane ListScroll;
    private javax.swing.JFormattedTextField PriceImput;
    private javax.swing.JLabel PriceTittle;
    private javax.swing.JButton ReloadButton;
    private javax.swing.JTextField SellPriceImput;
    private javax.swing.JButton TradeButton;
    private javax.swing.JTable TradeListTable;
    private javax.swing.JLabel TradeTittle;
    private javax.swing.JScrollPane VmrScroll;
    private javax.swing.JTable VmrTable;
    // End of variables declaration//GEN-END:variables
}
