package Model;
// Generated 30/06/2018 03:39:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadollave generated by hbm2java
 */
public class Estadollave  implements java.io.Serializable {


     private Integer idestado;
     private String estadollaveNombre;
     private Set keyses = new HashSet(0);

    public Estadollave() {
    }

    public Estadollave(String estadollaveNombre, Set keyses) {
       this.estadollaveNombre = estadollaveNombre;
       this.keyses = keyses;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public String getEstadollaveNombre() {
        return this.estadollaveNombre;
    }
    
    public void setEstadollaveNombre(String estadollaveNombre) {
        this.estadollaveNombre = estadollaveNombre;
    }
    public Set getKeyses() {
        return this.keyses;
    }
    
    public void setKeyses(Set keyses) {
        this.keyses = keyses;
    }




}


