package Model;
// Generated 30/06/2018 03:39:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Keys generated by hbm2java
 */
public class Keys  implements java.io.Serializable {


     private Integer idkey;
     private Estadollave estadollave;
     private Double precioCompra;
     private Date fechaCompra;

    public Keys() {
    }

    public Keys(Estadollave estadollave, Double precioCompra, Date fechaCompra) {
       this.estadollave = estadollave;
       this.precioCompra = precioCompra;
       this.fechaCompra = fechaCompra;
    }
   
    public Integer getIdkey() {
        return this.idkey;
    }
    
    public void setIdkey(Integer idkey) {
        this.idkey = idkey;
    }
    public Estadollave getEstadollave() {
        return this.estadollave;
    }
    
    public void setEstadollave(Estadollave estadollave) {
        this.estadollave = estadollave;
    }
    public Double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Double precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }




}


